### PR TITLE
Lang2018pointpillars 1+joshpapermaster

### PR DESCRIPTION
**Pull request by joshpapermaster**

### CODE REVIEW

**Comment by DartingMelody** [comment]
Hi @joshpapermaster, You have written an amazing summary. I have added some minor comments to polish it a bit.

**Comment by joshpapermaster** [comment]
> Hi @joshpapermaster, You have written an amazing summary. I have added some minor comments to polish it a bit.

Hey @DartingMelody, I don't think I'm able to see your comments. You may have forgotten to hit "submit" on the review (happened to me once). But please let me know if I'm not looking in the right place or anything.

**Comment by DartingMelody** [comment]
> > Hi @joshpapermaster, You have written an amazing summary. I have added some minor comments to polish it a bit.
> 
> Hey @DartingMelody, I don't think I'm able to see your comments. You may have forgotten to hit "submit" on the review (happened to me once). But please let me know if I'm not looking in the right place or anything.

Hey  @joshpapermaster, Yes, I missed the submit. Sorry for the hustle. Can you check now, if you can see the reviews.

**Comment by joshpapermaster** [comment]
> > > Hi @joshpapermaster, You have written an amazing summary. I have added some minor comments to polish it a bit.
> 
> > 
> 
> > Hey @DartingMelody, I don't think I'm able to see your comments. You may have forgotten to hit "submit" on the review (happened to me once). But please let me know if I'm not looking in the right place or anything.
> 
> 
> 
> Hey  @joshpapermaster, Yes, I missed the submit. Sorry for the hustle. Can you check now, if you can see the reviews. 

@DartingMelody I see them thank you!

**Review by zhaoyue-zephyrus — APPROVED** [review]

**Pull request merged**
