### PR TITLE
cui2019class-balanced_1

### PR DESCRIPTION
**Pull request by jordi1215**
@chengchunhsu Sorry I am behind this week again. I am going to put up just an outline for now. Feel free to give me anything that you find interesting that I should include. Sorry about this and thanks in advance!

### CODE REVIEW

**Comment by chengchunhsu** [comment]
Sorry I missed the previous comment. I just quickly sketched the paper and review and here are my comments.

I hope my comments can still do some help.



1. I like the presentation of the problem definition. It indeed helps the readers understand the problem better.

2. Given that the experiments are conducted based on Class-balanced Focal loss (eq12) rather than the Class-balanced loss (eq6). IMO it would be better if the review can cover some Focal Loss content.

3. (cont.) Focal Loss actually has some special characteristics, e.g., it is computed based on sigmoid and sigmoid treat each class independently unlike CE loss. Plus, Focal Loss itself is designed as a solution for the class imbalance problem, thus the comparison of FL and Class-balanced FL actually can bring some key insights to the readers.

3. It would be great if the review can cover some analysis on hyper-parameter β since it is the most crucial parameter of the proposed method.

**Comment by jordi1215** [comment]
> Sorry I missed the previous comment. I just quickly sketched the paper and review and here are my comments.
> 
> I hope my comments can still do some help.
> 
> 1. I like the presentation of the problem definition. It indeed helps the readers understand the problem better.
> 2. Given that the experiments are conducted based on Class-balanced Focal loss (eq12) rather than the Class-balanced loss (eq6). IMO it would be better if the review can cover some Focal Loss content.
> 3. (cont.) Focal Loss actually has some special characteristics, e.g., it is computed based on sigmoid and sigmoid treat each class independently unlike CE loss. Plus, Focal Loss itself is designed as a solution for the class imbalance problem, thus the comparison of FL and Class-balanced FL actually can bring some key insights to the readers.
> 4. It would be great if the review can cover some analysis on hyper-parameter β since it is the most crucial parameter of the proposed method.

It helps a lot thank you!

**Comment by jordi1215** [comment]
@zhaoyue-zephyrus , hi! Last time I tried to put in some latex math into my review it didn't render properly. I looked into how other students did it and found out they used the "$$" around the math part. I am not sure if this is what made it work or if there is something else that I am missing. Please let me know if my math is not rendering so I can fix it. Thanks!

**Comment by zhaoyue-zephyrus** [comment]
@jordi1215 yes, ```$$ $$``` should work. I'll check before I push into the course page.

**Review by zhaoyue-zephyrus — APPROVED** [review]

**Pull request merged**
