### PR TITLE
dong2021attention+ishanashah

### PR DESCRIPTION
**Pull request by ishanashah**

### CODE REVIEW

**Comment by ishanashah** [comment]
@jordi1215 Hi, my summary is ready for review.

**Comment by jordi1215** [comment]
@ishanashah  Hello! I am not the reviewer but the coder for this project :)

**Comment by ishanashah** [comment]
@jordi1215 LOL sorry about that
@kelseyball Hi, my summary is ready for review.

**Review by kelseyball — COMMENTED** [review]
Hey nice review! Here are a couple comments:
-  Maybe mention: what is the problem with rank collapse? (as far as I understand: each path converges to a rank-1 matrix with identical rows, implying that each input token gets an identical output representation)
- Might help to explain the y-axis for the first figure
- An organizational note: might help to have some subheadings to structure your summary (main idea, problem, solution, etc. or w/e)

**Review by zhaoyue-zephyrus — APPROVED** [review]

**Pull request merged**
