### PR TITLE
desai2020virtex Summary 1

### PR DESCRIPTION
**Pull request by liaojh1998**
Hey, sorry about the delay. I'm currently working on this and will be done by Saturday afternoon!

### CODE REVIEW

**Comment by trowk** [comment]
Hello! It seems like you've finished the first two sections and all you need to do is add a discussion of the experiments the paper performed. I don't think you need to discuss all the experiments the researchers performed like the ablations section, but it's up to you!

**Comment by liaojh1998** [comment]
Hey @trowk, thank you so much for the review! I added the experiments for frozen features and fine-tuning. I also included a summary of ablations and added caption attention visualizations. The data efficiency figure has also been added. Let me know if there's anything that needs fixing.

**Comment by trowk** [comment]
Everything looks great!

**Review by trowk — COMMENTED** [review]
The review looks great and is ready to be merged!

**Review by zhaoyue-zephyrus — APPROVED** [review]

**Pull request merged**
