### PR TITLE
Update radford2018improving_1.md

### PR DESCRIPTION
**Pull request by chengchunhsu**

### CODE REVIEW

**Comment by chengchunhsu** [comment]
It seems like I modified the wrong file a few days ago (i.e., radford2018improving_1.md instead of radford2018improving_2.md)

I have moved+upadted the content to radford2018improving_2.md.
Is it possible not to pull up the wrong part?

**Comment by zhaoyue-zephyrus** [comment]
@chengchunhsu Could you try rolling back `radford2018improving_1.md` to what it used to be and push again?

**Comment by zhaoyue-zephyrus** [comment]
@marcobueso any comment on this summary?

**Comment by marcobueso** [comment]
Hi,
This is a good summary. It is brief and captures the main idea of the paper.
Maybe, you could be a bit more thorough on the core idea description, simply to provide more context.
Also for some reason, I was unable to see the images, but that might be on my end only.
Maybe at the end, quickly mention the current usage of this method, which to my understanding, has been overshadowed by other methods since its publication.

**Comment by chengchunhsu** [comment]
> @chengchunhsu Could you try rolling back `radford2018improving_1.md` to what it used to be and push again?

I just rolled it back to the default version.

**Review by zhaoyue-zephyrus — APPROVED** [review]

**Comment by zhaoyue-zephyrus** [comment]
@chengchunhsu Thank you. I'll merge this after today's class.

**Pull request merged**
