### PR TITLE
Bahdanau2014neural 1

### PR DESCRIPTION
**Pull request by SShivang**
I have started a draft of summary.

### CODE REVIEW

**Review by slycane9 — CHANGES_REQUESTED** [review]
I don't see the Bahdanau paper in this pull request so I assume this was an error.  The Wu paper is on Group Norm which was last week.

**Comment by SShivang** [comment]
Yes that is an error

**Comment by SShivang** [comment]
@slycane9 fixed now.

**Comment by slycane9** [comment]
Go into more details about why the decoder changes improve the translation accuracy.  Also, the model actually performs better on longer sentences than the model they tested against, due to the vectors not being a fixed size.  Maybe expand more on the results in general as well and talk about how the model compares to the state of the art at  the time.

**Comment by SShivang** [comment]
Ready to merge

**Comment by zhaoyue-zephyrus** [comment]
@SShivang Can you remove the artifacts related to group norm?

**Comment by SShivang** [comment]
@zhaoyue-zephyrus Does that work?

**Comment by zhaoyue-zephyrus** [comment]
@SShivang Great! It looks good to me now.  I am going to merge this

**Review by zhaoyue-zephyrus — APPROVED** [review]

**Pull request merged**
