### PR TITLE
Sutskever2013on specfazhou

### PR DESCRIPTION
**Pull request by specfazhou**
My draft summary for sutskever2013on_1

### CODE REVIEW

**Review by rll2396 — COMMENTED** [review]
explain what momentum is briefly since it is a very important term to the paper and might not be obvious to everyone

thought the discussion on why previous methods failed ("transient"/final phase of learning and meta-parameter schedule) was pretty interesting, could be worth adding

could elaborate on why tuning the momentum parameter is important

clarify first/second-order (perhaps only during the presentation) and ESN/EGN? (you bring up the acronym without mentioning what they stand for)

**Comment by specfazhou** [comment]
I have modified my summary, it should be the final draft

**Comment by zhaoyue-zephyrus** [comment]
@specfazhou Hi, could you modify a bit so that only one file is changed in this pr?

**Comment by specfazhou** [comment]
Sure, but what do you mean by "only one file is changed in this pr?"

Best,
Zhou
________________________________

**Comment by zhaoyue-zephyrus** [comment]
Never mind. I've fixed it myself.

**Comment by specfazhou** [comment]
Ok, great!
________________________________

**Pull request merged**
